import type { Metadata } from 'next';
import './globals.css';
import Container from '@/components/Layout/Container';
import Header from '@/components/Layout/Header';
import Footer from '@/components/Layout/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Container>
          <Header />
        </Container>

        <main className="flex-1 w-full">
          <Container>{children}</Container>
        </main>

        <Container>
          <Footer />
        </Container>
      </body>
    </html>
  );
}
