import Footer from '@/components/layout/Footer';
import Header from '@/components/layout/Header';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="antialiased">
        <div className="max-w-125 mx-auto w-full px-2 flex flex-col gap-7">
          <Header />

          <main className="flex-1 w-full animate-fade-in-up">
            {children}
          </main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
